
'use client'
// app/layout.tsx
import "@/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HeroUIProvider } from "@heroui/react";
import ReduxProvider from "./redux/provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <HeroUIProvider>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
