name: Snyk Security Scan

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  snyk-frontend:
    name: Scan Next.js Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - uses: snyk/actions/node@master
        with:
          args: test --severity-threshold=high --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYKKEYNEXT }}