name: SonarCloud Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar-frontend:
    name: Analyze Next.js Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SNYKKEYNEXT }}
          SONAR_PROJECT_KEY: tepakorn11_nextJsFronted
          SONAR_ORGANIZATION: tepakorn11